### ISSUE TITLE
ExternalModules::query complains of missing parameters

### ISSUE THREAD

**Issue by pbchase** [ctsit/warn_users_of_pending_suspension#19]
Terry Smith of ua.edu reports:

> From: Terry Smith <xxx@medadmin.arizona.edu>
> Date: Monday, January 27, 2020 at 3:59 PM
> To: xxx@ufl.edu 
> Subject: account suspension warning
> 
> Hi all
>  
> I’m getting a Cron job failure for the warn users of pending suspension external module. This appears to be related to the latest version of REDCap (9.6.3). I have included the error message below. Are you familiar with this or are you seeing this same message on your end?
>  
> Thanks for looking at this because I really like the module.
> Best regards
> terry
>  
> [This message was automatically generated by REDCap]
> 
> Cron job 'warn_users_account_suspension_cron' failed for External Module 'warn_users_of_pending_suspension'.
> 
> Exception: Exception: An array of parameters is required as the second argument to the query method to encourage use of prepared statements. If no parameters are needed, an empty array must be specified to show that the use of a parameters was considered. in 
> D:\inetpub\redcap.uahs.arizona.edu\redcap_v9.6.3\ExternalModules\classes\ExternalModules.php:2166
>
> Stack trace:
> #0 D:\inetpub\redcap.uahs.arizona.edu\modules\warn_users_of_pending_suspension_v2.0.3\ExternalModule.php(97): ExternalModules\ExternalModules::query('select * from (...')
> #1 D:\inetpub\redcap.uahs.arizona.edu\redcap_v9.6.3\ExternalModules\classes\ExternalModules.php(4611): SuspensionWarning\ExternalModule\ExternalModule->warn_users_account_suspension_cron(Array)
> #2 D:\inetpub\redcap.uahs.arizona.edu\redcap_v9.6.3\Classes\Cron.php(295): ExternalModules\ExternalModules::callCronMethod('65', 'warn_users_acco...')
> #3 D:\inetpub\redcap.uahs.arizona.edu\redcap_v9.6.3\cron.php(22): Cron->execute()
> #4 D:\inetpub\redcap.uahs.arizona.edu\cron.php(11): include('D:\\inetpub\\redc...')
> #5 {main}
> 
> URL: http://
> Server: redcap.uahs.arizona.edu (com-redcap-web)
> Module Name: Warn Users of Pending Suspension (warn_users_of_pending_suspension)
> Module Author(s): xxx@ufl.edu
> Run Time: 0 seconds

**Comment by pbchase** [comment]
@ChemiKyle, Mark said we were doing something unsupported. See https://github.com/vanderbilt/redcap-external-modules/issues/246 I think we'll have to mod our code.

**Comment by pbchase** [comment]
Addressed by PR #20.
